@startuml
left to right direction
actor Administrador as Admin
rectangle Sistema {
  Admin --> (Visualizar inventario) : [101]
  Admin --> (Agregar producto) : [102]
  Admin --> (Actualizar cantidad) : [103]
  Admin --> (Eliminar producto) : [104]
}
@enduml


