@startuml
left to right direction
actor Usuario as User
rectangle Sistema {
  User --> (Seleccionar producto) : [111]
  (Seleccionar producto) .. (Verificar disponibilidad) : <<include>> [1.1]
  (Verificar disponibilidad) -- (Ingresar cantidad) : <<include>> [1.2]
  (Ingresar cantidad) -- (Calcular total) : <<include>> [1.3]
  (Calcular total) -- (Confirmar venta) : <<include>> [1.4]
  (Confirmar venta) -- (Actualizar inventario) : <<include>> [1.5]
}
@enduml
